# Generated by Django 5.1.4 on 2024-12-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_courier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
