# Generated by Django 5.1.4 on 2025-01-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_courier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='user',
        ),
    ]
