# Generated by Django 5.1.4 on 2025-01-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_courier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='monthly_order_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
