# Generated by Django 5.1.4 on 2025-05-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_courier_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='monthly_order_count',
        ),
    ]
