# Generated by Django 5.1.4 on 2025-05-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='current_location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Текущая широта'),
        ),
        migrations.AddField(
            model_name='courier',
            name='current_location_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Текущая долгота'),
        ),
    ]
