# Generated by Django 5.1.4 on 2025-05-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_courier_current_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, help_text='Опишите содержимое заказа', null=True, verbose_name='Описание заказа'),
        ),
    ]
