# Generated by Django 5.1.4 on 2025-05-11 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='orders.courier')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='orders.customer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='orders.order')),
            ],
            options={
                'unique_together': {('courier', 'order')},
            },
        ),
    ]
